### PR TITLE
* seq.el: Add seq-mapn

### PR DESCRIPTION
**Pull request by Malabarba**
I've missed this a couple of times before.

### CODE REVIEW

**Comment by NicolasPetton** [comment]
Ok, let me try to shamelessly make you do more work on seq.el :-)

I'd definitely be interested, if you would:
- Write unit tests for it
- Make it use `seq-map`, not `mapcar`[1]
- Add the new function in the readme
- Write a generic version in Emacs master (and add the tests there too)
- Add documentation in the sequences.texi file in Emacs master

[1] `seq-map` is better, because it will work on "new" seq types, like the one defined in `stream.el`. This way `seq.el` remains extensible.

**Comment by Malabarba** [comment]
Should I bump the version too?

**Comment by NicolasPetton** [comment]
Artur Malabarba notifications@github.com writes:

> Should I bump the version too?

Yes!

**Comment by Malabarba** [comment]
All done here. And here's the generic version I'll apply

```
(cl-defgeneric seq-mapn (function sequence &rest seqs)
  "Like `seq-map' but FUNCTION is mapped over all SEQS.
The arity of FUNCTION must match the number of SEQS, and the
mapping stops on the shortest sequence.
Return a list of the results.

\(fn FUNCTION SEQS...)"
  (let ((result nil)
        (seqs (seq-map (lambda (s) (seq-into s 'list))
                       (cons sequence seqs))))
    (while (not (memq nil seqs))
      (push (apply function (seq-map #'car seqs)) result)
      (setq seqs (seq-map #'cdr seqs)))
    (nreverse result)))
```

**Comment by NicolasPetton** [comment]
Great, thank you!

One detail, could you rename the argument `seqs` to `sequences` in the generic version?

**Comment by Malabarba** [comment]
Sure. :+1:

**Comment by Malabarba** [comment]
FTR. Emacs master pushed as well.

**Comment by NicolasPetton** [comment]
That's great, thank you!

**Pull request merged**
